[tool.pyright]
venv = ".venv"
include = ["*.py", "tests"]
exclude = ["**/node_modules",
    "**/__pycache__"
]

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.11"
pythonPlatform = "Linux"
